_ikto_testportal_emu_gui:
    resource: "@IktoTpEmuGuiBundle/Resources/config/routing.yml"
    prefix:   /

_ikto_testportal_emu_api:
    resource: "@IktoTpEmuApiBundle/Resources/config/routing.yml"
    prefix:   /
