ikto_testportal_emu_main:
    path: /
    defaults:
        _controller: IktoTpEmuGuiBundle:Default:index
    methods: [ GET ]

ikto_testportal_emu_check:
    path: /
    defaults:
        _controller: IktoTpEmuGuiBundle:Default:check
    methods: [ POST ]
